init: main service
anji-mito/java-explore-with-me pull request #4
Opened 2023-09-17 11:47 UTC by anji-mito

2023-10-20 00:12 UTC, anji-mito commented
Не понимаю почему, но падают сервисы в докере при использовании yaml
Например для stats был такой
server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          format_sql: true
          show_sql: true
          use_sql_comments: true
  sql:
    init:
      mode: always
  mvc:
    throw-exception-if-invalid: true
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats-db
    username: asd
    password: asd

---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:stats-db
    username: test
    password: test

2023-10-20 23:04 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-10-20 23:04 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/request/service/ParticipationRequestServiceImpl.java
> +    public List<ParticipationRequestDto> getRequestsByUser(long userId) {
???

А если взглянуть на интерфейс, так оказывается что этот метод и не используется нигде!

2023-10-22 11:54 UTC, FanaticFiz approved these changes
Принимается

2023-10-22 13:30 UTC, merged